all:
	nvcc -std=c++11 hello.cu -o hello

#hello.o: hello.cu
#	/opt/cuda/bin/nvcc -std=c++11 -c hello.cu

#all: hello.o
#	#g++ -o hello hello.o -L/usr/local/cuda-7.5/lib64 -I/usr/local/cuda-7.5/include -lopenblas -lpthread -lcudart -lcublas -fopenmp -O3 -Wextra -std=c++11
#	g++ -o hello hello.o -L/usr/local/cuda-7.5/lib64 -I/usr/local/cuda-7.5/include
#	-lpthread
#	#-lopenblas
#	#-lcudart
#	#-lcublas
#	-fopenmp -O3 -Wextra -std=c++11
